spring:
  application:
    name: barber-saas-backend

  profiles:
    default: local

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: ${APP_TIMEZONE:America/Sao_Paulo}

  jackson:
    time-zone: ${APP_TIMEZONE:America/Sao_Paulo}
    date-format: yyyy-MM-dd HH:mm:ss

server:
  port: ${SERVER_PORT:8080}
